### ISSUE TITLE
Atividade 16

### ISSUE THREAD

**Issue by B3nedito** [ProfRonan/is-prime-B3nedito#2]
Print("Digite um número")
a = int(input(">>>"))
If a< 1 :
          Print("número invalido")
Else:
         
       If a== 2 or   a == 3 or a== 5 or a == 7:
              Print("primo")

      Elif a % 2 == 0 or a % 3== 0 or a % 5 == 0 or a % 7 == 0 or a == 1:
        
             Print(" não primo")
      
        Else:
             Print("primo")

**Comment by SeuRonao** [comment]
Era para ter feito um commit, o número 100000001 ele diz que é primo ou não?
